async function handleWorkoutComplete(event){const summary=event.detail;await db.put('sessions',summary);state.sessions=(await db.getAll('sessions')).sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));const card=$('#workoutComplete');card.replaceChildren(el('p',{className:'eyebrow',text:'Session complete'}),el('h2',{text:summary.planName}),el('p',{text:`${summary.completedSets} set${summary.completedSets===1?'':'s'} recorded locally.`}),el('div',{className:'button-row'},[el('a',{className:'button primary',text:'View progress',attrs:{href:'#progress'}}),el('a',{className:'button secondary',text:'Plan another',attrs:{href:'#today'}})]));renderWorkout();toast('Workout saved locally.');if(state.settings.sound)beep(660,.2)}
function renderProgress(){
  const sessions=state.sessions,completedSets=sessions.reduce((sum,session)=>sum+(session.completedSets??0),0),uniqueExercises=new Set(sessions.flatMap(session=>session.items?.map(item=>item.exerciseId)??[])).size,latest=sessions[0]?.completedAt?new Date(sessions[0].completedAt).toLocaleDateString():'—';$('#progressMetrics').replaceChildren(metric('Sessions',sessions.length),metric('Completed sets',completedSets),metric('Exercises practised',uniqueExercises),metric('Latest session',latest));
  const counts=new Map();sessions.forEach(session=>session.items?.forEach(item=>{const family=state.exerciseMap.get(item.exerciseId)?.familyLabel??'Other';counts.set(family,(counts.get(family)??0)+1)}));const max=Math.max(1,...counts.values()),coverage=$('#familyCoverage');coverage.replaceChildren();if(!counts.size)coverage.append(el('p',{text:'Complete a workout to see movement coverage.'}));[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).forEach(([family,count])=>coverage.append(el('div',{className:'bar-row'},[el('span',{text:family}),el('div',{className:'bar-track'},el('span',{attrs:{style:`width:${(count/max)*100}%`}})),el('strong',{text:String(count)})])));
  const history=$('#sessionHistory');history.replaceChildren();if(!sessions.length)history.append(el('p',{text:'No sessions recorded yet.'}));sessions.slice(0,10).forEach(session=>history.append(el('div',{className:'session-row'},[el('strong',{text:session.planName}),el('small',{text:`${new Date(session.completedAt).toLocaleString()} · ${session.completedSets} sets`})])));
}
function metric(label,value){return el('div',{className:'metric-card'},[el('strong',{text:String(value)}),el('small',{text:label})])}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.94;utterance.pitch=1;window.speechSynthesis.speak(utterance)}
function beep(frequency=440,duration=.1){try{const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return;const context=new Context(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.04,context.currentTime+.01);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+duration);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+duration+.02);oscillator.addEventListener('ended',()=>context.close())}catch{}}
function download(name,content,type='application/json'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),link=el('a',{attrs:{href:url,download:name}});document.body.append(link);link.click();link.remove();URL.revokeObjectURL(url)}
function downloadCurrentPlan(){if(state.currentPlan)download('calisthenics-coach-session.json',JSON.stringify(state.currentPlan,null,2))}
async function exportData(){const payload=await db.exportAll();download(`calisthenics-coach-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2))}
async function importData(file){if(!file||file.size>5_000_000)throw new Error('Backup file is too large.');const payload=JSON.parse(await file.text());await db.importAll(payload);state.sessions=(await db.getAll('sessions')).sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));state.customProgrammes=await db.getAll('customProgrammes');renderProgrammes();renderProgress();toast('Backup imported.')}
async function deleteAllData(){if(!confirm('Delete every local session, custom programme and preference? This cannot be undone.'))return;await db.deleteAll();state.sessions=[];state.customProgrammes=[];state.settings={voice:true,sound:true,reducedMotion:false};applySettings();renderProgrammes();renderProgress();toast('Local data deleted.')}
function applySettings(){$('#voiceSetting').checked=state.settings.voice;$('#soundSetting').checked=state.settings.sound;$('#motionSetting').checked=state.settings.reducedMotion;document.body.classList.toggle('reduced-motion',state.settings.reducedMotion)}
async function updateSetting(key,value){state.settings[key]=value;await db.setPreference(key,value);applySettings()}
function bindEvents(){
  window.addEventListener('hashchange',route);$('#menuButton').addEventListener('click',()=>{const nav=$('#primaryNav');nav.classList.toggle('open');$('#menuButton').setAttribute('aria-expanded',String(nav.classList.contains('open')))});$('#energyInput').addEventListener('input',event=>{$('#energyOutput').textContent=`${event.target.value} / 5`});$('#plannerForm').addEventListener('submit',generateCurrentPlan);
  ['#exerciseSearch','#familyFilter','#difficultyFilter','#equipmentTierFilter','#trackingFilter','#quietFilter'].forEach(selector=>$(selector).addEventListener(selector==='#exerciseSearch'?'input':'change',renderLibrary));$('#startGeneratedButton').addEventListener('click',()=>state.currentPlan&&startWorkout(state.currentPlan));$('#saveGeneratedButton').addEventListener('click',saveCurrentPlan);$('#downloadPlanButton').addEventListener('click',downloadCurrentPlan);$('#openBuilderButton').addEventListener('click',()=>{renderBuilder();$('#builderDialog').showModal()});$('#saveBuilderButton').addEventListener('click',saveBuilder);$('#clearBuilderButton').addEventListener('click',()=>{state.builderItems=[];renderBuilder()});$('#plusRepButton').addEventListener('click',()=>state.workout.addRep(1));$('#minusRepButton').addEventListener('click',()=>state.workout.addRep(-1));$('#completeSetButton').addEventListener('click',()=>state.workout.completeSet());$('#skipExerciseButton').addEventListener('click',()=>{state.workout.skip();announceExercise()});$('#extendRestButton').addEventListener('click',()=>state.workout.extendRest(15));$('#pauseWorkoutButton').addEventListener('click',()=>state.workout.togglePause());$('#stopWorkoutButton').addEventListener('click',()=>{if(confirm('Stop this workout? Completed sets will not be saved.')){state.workout.stop();renderWorkout()}});
  $('#exportDataButton').addEventListener('click',exportData);$('#exportSettingsDataButton').addEventListener('click',exportData);$('#importDataInput').addEventListener('change',event=>importData(event.target.files[0]).catch(error=>toast(error.message)));$('#deleteDataButton').addEventListener('click',deleteAllData);$('#voiceSetting').addEventListener('change',event=>updateSetting('voice',event.target.checked));$('#soundSetting').addEventListener('change',event=>updateSetting('sound',event.target.checked));$('#motionSetting').addEventListener('change',event=>updateSetting('reducedMotion',event.target.checked));$('#installButton').addEventListener('click',async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('#installButton').hidden=true});window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();state.installPrompt=event;$('#installButton').hidden=false});state.workout.addEventListener('started',renderWorkout);state.workout.addEventListener('changed',renderWorkout);state.workout.addEventListener('tick',renderWorkout);state.workout.addEventListener('complete',handleWorkoutComplete);state.workout.addEventListener('stopped',renderWorkout);
}
async function registerServiceWorker(){if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./service-worker.js',{scope:'./'})}catch(error){console.warn('Service worker registration failed',error)}}}
async function init(){
  $('#appVersion').textContent=APP_VERSION;equipmentChecks($('#plannerEquipment'),'equipment');try{await loadData();renderFamilyOptions();renderLibrary();renderProgrammes();renderProgress();renderBuilder();applySettings();bindEvents();route();await registerServiceWorker()}catch(error){console.error(error);toast('The app could not load its local catalogue.');$('#generatedPlan').textContent=error.message}
}
init();
