const LEVEL_RANK = { foundation:0, beginner:1, intermediate:2, advanced:3 };
const IMPACT_RANK = { none:0, low:1, moderate:2, high:3 };
const GOAL_FAMILIES = {
  balanced:['squat-knee','horizontal-push','hinge-glute','pull-back','anterior-core','balance'],
  strength:['squat-knee','horizontal-push','hinge-glute','pull-back','anterior-core'],
  calisthenics:['horizontal-push','pull-back','vertical-push','anterior-core','locomotion'],
  core:['anterior-core','lateral-core','hinge-glute','locomotion'],
  conditioning:['low-cardio','locomotion','squat-knee','anterior-core'],
  mobility:['mobility','balance','hinge-glute'], balance:['balance','squat-knee','hinge-glute','mobility']
};
export function stableHash(text){let hash=2166136261;for(let i=0;i<text.length;i+=1){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619)}return hash>>>0}
function seededRandom(seed){let state=seed>>>0;return()=>{state+=0x6D2B79F5;let t=state;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
function supportedEquipment(exercise,selected){if(!exercise.equipment?.length)return true;return exercise.equipment.every(item=>selected.includes(item))}
function eligible(exercise,options){const allowedLevel=LEVEL_RANK[options.level]??1,allowedImpact=IMPACT_RANK[options.impact]??1;if(LEVEL_RANK[exercise.difficulty]>allowedLevel)return false;if(IMPACT_RANK[exercise.impact]>allowedImpact)return false;if(!supportedEquipment(exercise,options.equipment))return false;if(options.quiet&&exercise.noise!=='quiet')return false;if(options.smallSpace&&exercise.space!=='small')return false;return true}
function scoreExercise(exercise,context){const preferredFamilies=GOAL_FAMILIES[context.goal]??GOAL_FAMILIES.balanced;let score=preferredFamilies.includes(exercise.family)?40:0;score+=exercise.goals.includes(context.goal)?28:0;score+=8-Math.abs((LEVEL_RANK[exercise.difficulty]??0)-(LEVEL_RANK[context.level]??1))*4;score+=exercise.equipment.length===0?4:0;score+=exercise.impact==='none'||exercise.impact==='low'?3:0;if(context.recentExerciseIds.has(exercise.id))score-=20;if(context.energy<=2&&['mobility','balance','low-cardio'].includes(exercise.family))score+=8;if(context.energy>=4&&['strength','calisthenics'].some(goal=>exercise.goals.includes(goal)))score+=5;score+=context.random()*3;return score}
function chooseOne(pool,usedIds,context,family){const candidates=pool.filter(ex=>!usedIds.has(ex.id)&&(!family||ex.family===family)).map(ex=>({ex,score:scoreExercise(ex,context)})).sort((a,b)=>b.score-a.score||a.ex.name.localeCompare(b.ex.name));return candidates[0]?.ex??null}
function planItem(exercise,phase,energy){const p=exercise.prescription,setAdjustment=energy<=2?-1:energy>=5?1:0;return{exerciseId:exercise.id,phase,metric:p.type,target:energy<=2?Math.max(4,Math.round(p.target*.8)):p.target,sets:Math.max(1,Math.min(4,p.sets+setAdjustment)),restSeconds:energy<=2?p.restSeconds+20:p.restSeconds,coachingMode:p.type==='hold'||p.type==='duration'?'timer':'manual'}}
export function estimatePlanMinutes(items){const seconds=items.reduce((total,item)=>{const workPerSet=item.metric==='hold'||item.metric==='duration'?item.target:item.target*4;return total+(workPerSet+item.restSeconds)*item.sets},0);return Math.max(5,Math.round(seconds/60))}
export function generatePlan(exercises,options,recentSessions=[]){const dateKey=new Date().toISOString().slice(0,10),seed=stableHash(JSON.stringify({...options,dateKey})),random=seededRandom(seed),recentExerciseIds=new Set(recentSessions.slice(0,3).flatMap(session=>session.items?.map(item=>item.exerciseId)??[])),context={...options,random,recentExerciseIds},pool=exercises.filter(exercise=>eligible(exercise,options)),used=new Set(),selected=[];const warmFamilies=options.goal==='conditioning'?['low-cardio','mobility']:['mobility','low-cardio'];for(const family of warmFamilies){const ex=chooseOne(pool,used,context,family);if(ex){selected.push(planItem(ex,'warmup',Math.min(options.energy,3)));used.add(ex.id)}}const mainCount=options.duration<=15?3:options.duration<=25?4:options.duration<=35?5:6,mainFamilies=GOAL_FAMILIES[options.goal]??GOAL_FAMILIES.balanced;for(const family of mainFamilies){if(selected.filter(item=>item.phase==='main').length>=mainCount)break;const ex=chooseOne(pool,used,context,family);if(ex){selected.push(planItem(ex,'main',options.energy));used.add(ex.id)}}while(selected.filter(item=>item.phase==='main').length<mainCount){const ex=chooseOne(pool,used,context);if(!ex)break;selected.push(planItem(ex,'main',options.energy));used.add(ex.id)}for(const family of ['mobility','balance']){const ex=chooseOne(pool,used,context,family);if(ex){selected.push(planItem(ex,'cooldown',Math.min(options.energy,3)));used.add(ex.id);break}}return{id:`generated-${dateKey}-${seed}`,name:`${options.goal[0].toUpperCase()}${options.goal.slice(1)} ${options.duration}`,description:'A deterministic, explainable session built from your current preferences.',generatedAt:new Date().toISOString(),options,estimatedMinutes:estimatePlanMinutes(selected),items:selected}}
export function explainPlan(plan,exerciseMap){const families=[...new Set(plan.items.filter(i=>i.phase==='main').map(i=>exerciseMap.get(i.exerciseId)?.familyLabel).filter(Boolean))];return[`Built for a ${plan.options.level} level and approximately ${plan.options.duration} minutes.`,`Main movement coverage: ${families.join(', ')}.`,plan.options.quiet?'Only quiet movements were considered.':'Normal movement noise was allowed.',plan.options.smallSpace?'Only small-space movements were considered.':'Medium floor space was allowed.',`Impact ceiling: ${plan.options.impact}.`]}
